### ISSUE TITLE
Example responses have text 'undefined'

### ISSUE THREAD

**Issue by olliahonen** [kivra/developer.kivra.com#21]
It says 'undefined' above many of the example responses which gives the impression that there is something wrong.

<img width="120" alt="screen shot 2018-12-13 at 15 31 49" src="https://user-images.githubusercontent.com/1252732/49941871-60870b00-feec-11e8-9d69-447e6938994b.png">

**Comment by paolokivra** [comment]
@kbip is this because we do not use "links"? In my local rendering it looks OK:
![image](https://user-images.githubusercontent.com/31687891/55631274-f1ddfe00-57b7-11e9-923c-1a7cec89ce25.png)
But once published looks like this:
![image](https://user-images.githubusercontent.com/31687891/55631382-2baf0480-57b8-11e9-9734-2a25be758886.png)
I wonder whether "undefined" is where the renderer expects links?

**Comment by paolokivra** [comment]
Solved after last update from @kbip
